# Generated by Django 3.2.9 on 2021-11-30 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TA_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='office_hours',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='classtolab',
            name='lab_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_schedule.lab'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
