# Generated by Django 3.2.9 on 2021-12-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_schedule', '0002_auto_20211130_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
