# Generated by Django 3.2.9 on 2021-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_schedule', '0003_rename_user_id_personalinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='skills',
            field=models.CharField(default='', max_length=250),
        ),
    ]
